# Site
favicon: images/favicon.ico

# Personal info
name: Iain Angus
title: .NET & Azure Specialist
website: https://blog.sixfortyfour.com
website_title: Blog

# Social links
github_username: sixfortyfour
linkedin_username: irangus

# Build settings
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

# Analytics
goatcounter: whoami-sixfortyfour
